### ISSUE TITLE
How to handle Leela Zero's printsgf command?

### ISSUE THREAD

**Issue by zhanzhenzhen** [SabakiHQ/gtp#2]
Leela Zero's printsgf command dumps the SGF with many newlines. But GTP response in this lib only has the first line, which doesn't even contain any moves...

**Comment by yishn** [comment]
A GTP response ends with two consecutive new lines [as stated in the spec](https://www.lysator.liu.se/~gunnar/gtp/gtp2-spec-draft2/gtp2-spec.html#SECTION00036000000000000000). I've inspected the `printsgf` command of Leela Zero:

![Leela Zero printsgf](https://user-images.githubusercontent.com/9217349/46020991-ebbbe600-c0df-11e8-95c6-7d79a002f498.png)

Leela Zero incorrectly introduces two consecutive new lines before the SGF ends. That's why `gtp` assumes the response ends with the first line. Incidentally, Leela has the same problem. Please open an issue on Leela (Zero)'s repository.

**Comment by gcp** [comment]
Fixed in Leela Zero now, it'll be a while before I can go back and fix this in regular Leela though.
